### ISSUE TITLE
upgrade to latest purescript-parsing?

### ISSUE THREAD

**Issue by jamesdbrock** [flounders/purescript-datetime-parsing#1]
Nice library! I want to upgrade it to be compatible of new versions of purescript-parsing. Will you accept a PR for that?

**Comment by flounders** [comment]
Thank you! Yes, any pull requests are welcome.

**Comment by jamesdbrock** [comment]
Great. Also I'm linking to this from Related Packages https://github.com/purescript-contrib/purescript-parsing#related-packages

**Comment by flounders** [comment]
Thanks for working on this. I'm working on publishing the update to Pursuit this morning.

**Comment by jamesdbrock** [comment]
You might like this? https://github.com/purescript-contrib/governance/blob/main/pursuit-preregistry.md

**Comment by flounders** [comment]
Thank you for sharing that link, it was very helpful. I did a minor version bump, and everything looks good to me.
